sudo: false
language: python
python:
  - "2.7"
cache:
  - pip
before_install:
  - pip install --upgrade pip
install:
  - pip install -e .
  - pip install -r requirements-dev.txt
  - pip install coveralls
script:
  - flake8
  # Ensure plural expressions are not allowed in PO files
  # Disabled: need to find a better way of doing this
  #- grep -Rq "plural=EXPRESSION" --include \*.po locale/
  - py.test
after_success:
  - coveralls


jobs:
  include:
    - stage: test
    - stage: docker
      python: "2.7"
      sudo: required
      dist: trusty
      services: [docker]
      env:
        - IMAGE_NAME=praekeltfoundation/molo-iogt
        - REGISTRY_USER=praekeltorgdeploy
        - secure: "pnvFFZopJn0o7rlcT5sHkoC+ursFGPr50ORXCC5/daL5Mq17/d5fD858nPPRxqfk/+PQ2cugWz9CJQxsgI/55VuWhrUehqGDOwsVZht6nRAvzcTEV1Au7QlfXVx2tQDfLOCh5v3LYS6rKLROrwk+vYjrlSKAbTKqY3znjFQEOCTwATEQCMLj70mcWOw7YvQvk2MvgsoRKWZdQN8HXVs4hP4HmUkvJxW/G/o5omoCQYpEvntfxNwtOjJEahwvbTZgMaGE0v5HfDX8E5eVf4XYq5kJ2eOa7GhM1bfIcwqwqrIcNDJSwzh8jhCc+YW+mEI3KgpfsNXR0EFu8gNhd5Cc3/XNXCqwq6tKdoHM3MgR3rja5C3Ie2COBAJU3K9osnklDpgJeE8ZWZ8l2hIihtOL6CKxeFLLMRn9HgYXyo697SbUp8BU0n5t5dDcS84G5F/xWwEZQi+TCaCmWewc0G6fByR/UamJ7SS6pO1X8QS1g0jDmMpPLRNxyrSOlniz88H9KGW1afyMBq+d2ShpDBvg9zIK6CpaE2P164ecAFcdrbZTB0w3R9vNbxPSAVpcOuiROkP4vPwRqtukEZSboilcuQzD7oFbMSfFR4cc6d+/7xnVFMrKfqT+rYpAO0fWiuDq6ZPn8U3pDnKo2cdUajoNkzOgP+oq+5UQTILZHOdui3M="

      # Update Docker: we want some new docker build features
      install:
        - sudo apt-get update
        - sudo apt-get install -y -o Dpkg::Options::="--force-confold" docker-ce

      before_script:
        - molo_version="$(sed -nE 's/^molo\.core==(.*)$/\1/p' requirements.txt)"
        - docker pull "$IMAGE_NAME" || true
      script:
        - docker build --pull --cache-from "$IMAGE_NAME" --tag "$IMAGE_NAME" --build-arg MOLO_VERSION="$molo_version" .

      before_deploy:
        - pip install docker-ci-deploy==0.3.0
        - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
      deploy:
        - provider: script
          script: dcd --version "$(git rev-parse --short HEAD)" --version-latest "$IMAGE_NAME"
          on:
            branch: develop
        - provider: script
          script: dcd --tag "$TRAVIS_TAG" -- "$IMAGE_NAME"
          on:
            tags: true

      # Built steps inherited from the default stage that we don't want
      before_install: ignore
      after_success: []
