sudo: false
language: python
python:
  - "2.7"
cache:
  - pip
before_install:
  - pip install --upgrade pip
install:
  - pip install -e .
  - pip install -r requirements-dev.txt
  - pip install coveralls
script:
  - flake8
  # Check that the molo.core version in requirements.txt matches the version in the Docker image
  - |
    rv="$(sed -nE 's/^molo\.core==(.*)$/\1/p' requirements.txt)"
    dv="$(sed -nE 's/^FROM .*:(.*)-onbuild$/\1/p' Dockerfile)"
    if [ "$rv" != "$dv" ]; then echo "molo.core version mismatch: '$rv' != '$dv'"; return 1; fi
  - py.test
after_success:
  - coveralls
